### ISSUE TITLE
Play backward

### ISSUE THREAD

**Issue by jcornaz** [jcornaz/benimator#21]
As suggested in bevy discord: https://discord.com/channels/691052431525675048/691052431974465548/928336941643075606

### Potential API

Right now I am leaning toward a flag in the animation state component. So that it is possible to change the direction without changing the animation resource.

**Comment by jcornaz** [comment]
Yes, we could add a `Animation::from_indices(indices: impl IntoIterator<Item=usize>, duration: Duration)`, that would work.

We could also let `Animation` implement `FromIterator<Frame>`. 

That can give nice flexibility about how to build the animation asset.

But I am wondering, if having a `direction` flag in the animation state is not better. As that would make possible to change the direction of the animation while it is playing.

But one solution doesn't prevent the other of course. So, it's a matter of choosing which one to implement first.

Do you have a preference @aaneto. Do you need to *create* a reversed animation, or do you need to reverse an animation that is playing?

**Comment by jcornaz** [comment]
scratch my previous message. I think that indeed, allowing the create the animation from an iterator of indice is a simple and effective solution. I'm adding it right away ;-)

**Comment by aaneto** [comment]
@jcornaz I know the issue has been closed, but I suggested this solution because I see a reverse animation as another animation (walk vs reverse walk as two different "things").

**Comment by jcornaz** [comment]
Yes, I aggree. Which is why I went for your suggestion. Thanks @aaneto ;-)
