### ISSUE TITLE
Play Component Should be SparseSet

### ISSUE THREAD

**Issue by chrisburnor** [jcornaz/benimator#30]
Given that the play component is meant to trigger or pause animations, it should use SparseSet storage instead of Archetype storage to prevent archetype table copy.  This could be a significant overhead if one has a large number of animated entities that need to be paused all at once (say the user presses pause and that needs to pause all animations)

**Comment by jcornaz** [comment]
Hi, Yes that seems to make sense indeed.

**Note for potential contributors**:

With features/fixes I generally want an automated test. In this case - a perf improvement - I would like instead a performance benchmark.

But anyway, I am interested into sorting out the performance impact of the storage type. So if nobody takes the issue, I'll probably work on it this weekend.
