### ISSUE TITLE
Load SpriteSheetAnimation from a file

### ISSUE THREAD

**Issue by NiklasEi** [jcornaz/benimator#50]
Any chance to get support for loading a SpriteSheetAnimation from a file (behind a feature flag)? For example, one could load them from `.ron.animation` files.

**Comment by jcornaz** [comment]
Yes, we could support that.

Do you mind explaining your use case and what file format you would prefer?

**Comment by NiklasEi** [comment]
The use case is just that I would consider animations as assets, so they should live with the other assets in the asset directory.

I would suggest `ron` files.

**Comment by jcornaz** [comment]
> The use case is just that I would consider animations as assets

They are indeed assets.

> so they should live with the other assets in the asset directory

That logical consequence is not obvious to me. Why should they? 

I am not saying say they *should not*. but in order for me to say the *should*, there must be a usage scenario that is made easier and/or safer and/or faster if the assets is in a file.

> I would suggest `ron` files.

That's a bit vague. What should be the schema of that `ron` file?

**Comment by NiklasEi** [comment]
> > so they should live with the other assets in the asset directory
> 
> That logical consequence is not obvious to me. Why should they?
> 
> I am not saying say they _should not_. but in order for me to say that hey _should_, there must be a usage scenario that is made easier and/or safer and/or faster if the asset is in a file.

Imagine you are a content creator working on a Bevy game. You change a texture atlas to have more frames in some animation. This is a change in an asset file. To make it work, you currently also have to go into the code to adapt the animation. Your code might even not run anymore without changes in case you reduced the frames in the atlas.

> > I would suggest `ron` files.
> 
> That's a bit vague. What should be the schema of that `ron` file?

In my head, I just put a `#[derive(serde::Deserialize)]` on the asset type and used a simple asset loader to deserialize from ron files (see ['bevy_common_assets'](https://github.com/NiklasEi/bevy_common_assets) or [`bevy_asset_ron`](https://github.com/IyesGames/bevy_asset_ron)).

My main motivation for this issue: I usually use my crate `bevy_asset_loader` for games. It would be very nice if I could use `benimator` together with it. If you support loading an animation like this:
```rust
let handle: Handle<SpriteSheetAnimation> = asset_server.load("animations/coin_animation.animation");
```
it will be possible to have sprite sheet animations in `bevy_asset_loader` asset collections.

P.s.: sorry for the long silence

**Comment by jcornaz** [comment]
> Imagine you are a content creator working on a Bevy game. You change a texture atlas to have more frames in some animation. This is a change in an asset file. To make it work, you currently also have to go into the code to adapt the animation. Your code might even not run anymore without changes in case you reduced the frames in the atlas.

Ok. Do I understand well that the goal is to make it easier for *non-programers* to update the animation, so that they wouldn't have to edit rust code? 
That would be a valid use-case to me indeed. Though, I would rule out the `ron` format if that's the use-case. And use either a format specifically crafted for animation representation or use a format like `yaml`.

> In my head, I just put a `#[derive(serde::Deserialize)]` on the asset type and used a simple asset loader to deserialize from ron files (see [`bevy_common_assets`](https://github.com/NiklasEi/bevy_common_assets) or [`bevy_asset_ron`](https://github.com/IyesGames/bevy_asset_ron)).

That's an implementation detail. It describes how it could be achieved by benimator. Not what a user needs.

> My main motivation for this issue: I usually use my crate `bevy_asset_loader` for games. It would be very nice if I could use `benimator` together with it. If you support loading an animation like this:
> 
> ```rust
> let handle: Handle<SpriteSheetAnimation> = asset_server.load("animations/coin_animation.animation");
> ```
> 
> it will be possible to have sprite sheet animations in `bevy_asset_loader` asset collections.

Ah! Ok, now I get it. Yes, I guess that would be cool. I just have to figure out what file format I want then. I'll think about it, then probably directly implement the feature.

> P.s.: sorry for the long silence

No problem ;-)

**Comment by jcornaz** [comment]
Ok. So here's what I propose for a file format.

That would be `YAML`, with a scheme that looks like this:

```yaml
mode: ping-pong
frames:
  - index: 0
    duraton: 100 # ms
  - index: 1
    duraton: 100 # ms
  - index: 2
    duraton: 120 # ms
```

A `default-frame-duration` could also be used to avoid needless repetition. For example, the previous animation could be rewritten like this:

```yaml
mode: ping-pong
default-frame-duration: 100 # ms
frames:
  - index: 0
  - index: 1
  - index: 2
    duraton: 100 # ms
```

If all frames have the same duration, then it would be possible to use an even more succinct syntax:

```yaml
mode: ping-pong
default-frame-duration: 100 # ms
frames: [0, 1, 2]
```
