### ISSUE TITLE
Implement custom playback rates

### ISSUE THREAD

**Issue by flipbit03** [jcornaz/benimator#65]
I have an use case where I am extracting animation data from `.aseprite` files using `bevy_ase`. The process is very smooth and a nice thing is that, using the `benimator` feature of that crate, I am able to transform the extracted animation tags (frame ranges) into `SpriteSheetAnimation` objects which I can attach to my entities and use normally. That unexpected integration between the projects saved a lot of time on my end in that I don't have to reinvent an animation system from scratch :+1: :raised_hands: :heart: 

The problem is, I cannot dynamically alter the playback speed of the extracted animations, which would be useful in my project, as the hero can walk in different terrains and I'd like to speed up/slow down its walk cycle :runner:  without resorting to recreating the animation frames from scratch :dizzy_face: 

My idea is for us to have an additional optional component that, when applied, will reach `benimator`'s internal "update animation" system, altering the behavior of the update() function to take into consideration said multiplier :robot: :runner:

**Comment by jcornaz** [comment]
Sounds good to me. I'll try to give a look at your pull request soon.
